// Province and city data
export const provinces = [
  { code: 'Beijing', name: 'Beijing', value: 'Beijing', label: 'Beijing' },
  { code: 'Tianjin', name: 'Tianjin', value: 'Tianjin', label: 'Tianjin' },
  { code: 'Shanghai', name: 'Shanghai', value: 'Shanghai', label: 'Shanghai' },
  { code: 'Chongqing', name: 'Chongqing', value: 'Chongqing', label: 'Chongqing' },
  { code: 'Hebei', name: 'Hebei', value: 'Hebei', label: 'Hebei' },
  { code: 'Shanxi', name: 'Shanxi', value: 'Shanxi', label: 'Shanxi' },
  { code: 'Liaoning', name: 'Liaoning', value: 'Liaoning', label: 'Liaoning' },
  { code: 'Jilin', name: 'Jilin', value: 'Jilin', label: 'Jilin' },
  { code: 'Heilongjiang', name: 'Heilongjiang', value: 'Heilongjiang', label: 'Heilongjiang' },
  { code: 'Jiangsu', name: 'Jiangsu', value: 'Jiangsu', label: 'Jiangsu' },
  { code: 'Zhejiang', name: 'Zhejiang', value: 'Zhejiang', label: 'Zhejiang' },
  { code: 'Anhui', name: 'Anhui', value: 'Anhui', label: 'Anhui' },
  { code: 'Fujian', name: 'Fujian', value: 'Fujian', label: 'Fujian' },
  { code: 'Jiangxi', name: 'Jiangxi', value: 'Jiangxi', label: 'Jiangxi' },
  { code: 'Shandong', name: 'Shandong', value: 'Shandong', label: 'Shandong' },
  { code: 'Henan', name: 'Henan', value: 'Henan', label: 'Henan' },
  { code: 'Hubei', name: 'Hubei', value: 'Hubei', label: 'Hubei' },
  { code: 'Hunan', name: 'Hunan', value: 'Hunan', label: 'Hunan' },
  { code: 'Guangdong', name: 'Guangdong', value: 'Guangdong', label: 'Guangdong' },
  { code: 'Hainan', name: 'Hainan', value: 'Hainan', label: 'Hainan' },
  { code: 'Sichuan', name: 'Sichuan', value: 'Sichuan', label: 'Sichuan' },
  { code: 'Guizhou', name: 'Guizhou', value: 'Guizhou', label: 'Guizhou' },
  { code: 'Yunnan', name: 'Yunnan', value: 'Yunnan', label: 'Yunnan' },
  { code: 'Shaanxi', name: 'Shaanxi', value: 'Shaanxi', label: 'Shaanxi' },
  { code: 'Gansu', name: 'Gansu', value: 'Gansu', label: 'Gansu' },
  { code: 'Qinghai', name: 'Qinghai', value: 'Qinghai', label: 'Qinghai' },
  { code: 'Taiwan', name: 'Taiwan', value: 'Taiwan', label: 'Taiwan' },
  { code: 'Inner Mongolia', name: 'Inner Mongolia', value: 'Inner Mongolia', label: 'Inner Mongolia' },
  { code: 'Guangxi', name: 'Guangxi', value: 'Guangxi', label: 'Guangxi' },
  { code: 'Tibet', name: 'Tibet', value: 'Tibet', label: 'Tibet' },
  { code: 'Ningxia', name: 'Ningxia', value: 'Ningxia', label: 'Ningxia' },
  { code: 'Xinjiang', name: 'Xinjiang', value: 'Xinjiang', label: 'Xinjiang' },
  { code: 'Hong Kong', name: 'Hong Kong', value: 'Hong Kong', label: 'Hong Kong' },
  { code: 'Macau', name: 'Macau', value: 'Macau', label: 'Macau' }
];

// Helper function to convert string array to object array with code and name properties
const createCityObjects = (cityNames) => {
  return cityNames.map(name => ({ code: name, name: name }));
};

export const cities = {
  'Beijing': createCityObjects(['Dongcheng', 'Xicheng', 'Chaoyang', 'Fengtai', 'Shijingshan', 'Haidian', 'Mentougou', 'Fangshan', 'Tongzhou', 'Shunyi', 'Changping', 'Daxing', 'Huairou', 'Pinggu', 'Miyun', 'Yanqing']),
  'Tianjin': createCityObjects(['Heping', 'Hedong', 'Hexi', 'Nankai', 'Hebei', 'Hongqiao', 'Dongli', 'Xiqing', 'Jinnan', 'Beichen', 'Wuqing', 'Baodi', 'Binhai New Area', 'Ninghe', 'Jinghai', 'Jizhou']),
  'Shanghai': createCityObjects(['Huangpu', 'Xuhui', 'Changning', 'Jing\'an', 'Putuo', 'Hongkou', 'Yangpu', 'Minhang', 'Baoshan', 'Jiading', 'Pudong New Area', 'Jinshan', 'Songjiang', 'Qingpu', 'Fengxian', 'Chongming']),
  'Chongqing': createCityObjects(['Wanzhou', 'Fuling', 'Yuzhong', 'Dadukou', 'Jiangbei', 'Shapingba', 'Jiulongpo', 'Nan\'an', 'Beibei', 'Qijiang', 'Dazu', 'Yubei', 'Banan', 'Qianjiang', 'Changshou', 'Jiangjin', 'Hechuan', 'Yongchuan', 'Nanchuan', 'Bishan', 'Tongliang', 'Tongnan', 'Rongchang', 'Kaizhou', 'Liangping', 'Wulong']),
  'Hebei': createCityObjects(['Shijiazhuang', 'Tangshan', 'Qinhuangdao', 'Handan', 'Xingtai', 'Baoding', 'Zhangjiakou', 'Chengde', 'Cangzhou', 'Langfang', 'Hengshui']),
  'Shanxi': createCityObjects(['Taiyuan', 'Datong', 'Yangquan', 'Changzhi', 'Jincheng', 'Shuozhou', 'Jinzhong', 'Yuncheng', 'Xinzhou', 'Linfen', 'Lüliang']),
  'Liaoning': createCityObjects(['Shenyang', 'Dalian', 'Anshan', 'Fushun', 'Benxi', 'Dandong', 'Jinzhou', 'Yingkou', 'Fuxin', 'Liaoyang', 'Panjin', 'Tieling', 'Chaoyang', 'Huludao']),
  'Jilin': createCityObjects(['Changchun', 'Jilin City', 'Siping', 'Liaoyuan', 'Tonghua', 'Baishan', 'Songyuan', 'Baicheng', 'Yanbian']),
  'Heilongjiang': createCityObjects(['Harbin', 'Qiqihar', 'Jixi', 'Hegang', 'Shuangyashan', 'Daqing', 'Yichun', 'Jiamusi', 'Qitaihe', 'Mudanjiang', 'Heihe', 'Suihua', 'Da Hinggan Ling']),
  'Jiangsu': createCityObjects(['Nanjing', 'Wuxi', 'Xuzhou', 'Changzhou', 'Suzhou', 'Nantong', 'Lianyungang', 'Huai\'an', 'Yancheng', 'Yangzhou', 'Zhenjiang', 'Taizhou', 'Suqian']),
  'Zhejiang': createCityObjects(['Hangzhou', 'Ningbo', 'Wenzhou', 'Jiaxing', 'Huzhou', 'Shaoxing', 'Jinhua', 'Quzhou', 'Zhoushan', 'Taizhou', 'Lishui']),
  'Anhui': createCityObjects(['Hefei', 'Wuhu', 'Bengbu', 'Huainan', 'Ma\'anshan', 'Huaibei', 'Tongling', 'Anqing', 'Huangshan', 'Chuzhou', 'Fuyang', 'Suzhou', 'Lu\'an', 'Bozhou', 'Chizhou', 'Xuancheng']),
  'Fujian': createCityObjects(['Fuzhou', 'Xiamen', 'Putian', 'Sanming', 'Quanzhou', 'Zhangzhou', 'Nanping', 'Longyan', 'Ningde']),
  'Jiangxi': createCityObjects(['Nanchang', 'Jingdezhen', 'Pingxiang', 'Jiujiang', 'Xinyu', 'Yingtan', 'Ganzhou', 'Ji\'an', 'Yichun', 'Fuzhou', 'Shangrao']),
  'Shandong': createCityObjects(['Jinan', 'Qingdao', 'Zibo', 'Zaozhuang', 'Dongying', 'Yantai', 'Weifang', 'Jining', 'Tai\'an', 'Weihai', 'Rizhao', 'Linyi', 'Dezhou', 'Liaocheng', 'Binzhou', 'Heze']),
  'Henan': createCityObjects(['Zhengzhou', 'Kaifeng', 'Luoyang', 'Pingdingshan', 'Anyang', 'Hebi', 'Xinxiang', 'Jiaozuo', 'Puyang', 'Xuchang', 'Luohe', 'Sanmenxia', 'Nanyang', 'Shangqiu', 'Xinyang', 'Zhoukou', 'Zhumadian', 'Jiyuan']),
  'Hubei': createCityObjects(['Wuhan', 'Huangshi', 'Shiyan', 'Yichang', 'Xiangyang', 'Ezhou', 'Jingmen', 'Xiaogan', 'Jingzhou', 'Huanggang', 'Xianning', 'Suizhou', 'Enshi', 'Xiantao', 'Qianjiang', 'Tianmen', 'Shennongjia']),
  'Hunan': createCityObjects(['Changsha', 'Zhuzhou', 'Xiangtan', 'Hengyang', 'Shaoyang', 'Yueyang', 'Changde', 'Zhangjiajie', 'Yiyang', 'Chenzhou', 'Yongzhou', 'Huaihua', 'Loudi', 'Xiangxi']),
  'Guangdong': createCityObjects(['Guangzhou', 'Shenzhen', 'Zhuhai', 'Shantou', 'Foshan', 'Shaoguan', 'Zhanjiang', 'Zhaoqing', 'Jiangmen', 'Maoming', 'Huizhou', 'Meizhou', 'Shanwei', 'Heyuan', 'Yangjiang', 'Qingyuan', 'Dongguan', 'Zhongshan', 'Chaozhou', 'Jieyang', 'Yunfu']),
  'Hainan': createCityObjects(['Haikou', 'Sanya', 'Sansha', 'Danzhou', 'Wuzhishan', 'Qionghai', 'Wenchang', 'Wanning', 'Dongfang', 'Ding\'an', 'Tunchang', 'Chengmai', 'Lingao']),
  'Sichuan': createCityObjects(['Chengdu', 'Zigong', 'Panzhihua', 'Luzhou', 'Deyang', 'Mianyang', 'Guangyuan', 'Suining', 'Neijiang', 'Leshan', 'Nanchong', 'Meishan', 'Yibin', 'Guang\'an', 'Dazhou', 'Ya\'an', 'Bazhong', 'Ziyang', 'Ngawa', 'Garzê', 'Liangshan']),
  'Guizhou': createCityObjects(['Guiyang', 'Liupanshui', 'Zunyi', 'Anshun', 'Bijie', 'Tongren', 'Qianxinan', 'Qiandongnan', 'Qiannan']),
  'Yunnan': createCityObjects(['Kunming', 'Qujing', 'Yuxi', 'Baoshan', 'Zhaotong', 'Lijiang', 'Pu\'er', 'Lincang', 'Chuxiong', 'Honghe', 'Wenshan', 'Xishuangbanna', 'Dali', 'Dehong', 'Nujiang', 'Dêqên']),
  'Shaanxi': createCityObjects(['Xi\'an', 'Tongchuan', 'Baoji', 'Xianyang', 'Weinan', 'Yan\'an', 'Hanzhong', 'Yulin', 'Ankang', 'Shangluo']),
  'Gansu': createCityObjects(['Lanzhou', 'Jiayuguan', 'Jinchang', 'Baiyin', 'Tianshui', 'Wuwei', 'Zhangye', 'Pingliang', 'Jiuquan', 'Qingyang', 'Dingxi', 'Longnan', 'Linxia', 'Gannan']),
  'Qinghai': createCityObjects(['Xining', 'Haidong', 'Haibei', 'Huangnan', 'Hainan Prefecture', 'Golog', 'Yushu', 'Haixi']),
  'Taiwan': createCityObjects(['Taipei', 'New Taipei', 'Taoyuan', 'Taichung', 'Tainan', 'Kaohsiung', 'Keelung', 'Hsinchu', 'Chiayi']),
  'Inner Mongolia': createCityObjects(['Hohhot', 'Baotou', 'Wuhai', 'Chifeng', 'Tongliao', 'Ordos', 'Hulunbuir', 'Bayannur', 'Ulanqab', 'Hinggan', 'Xilingol', 'Alxa']),
  'Guangxi': createCityObjects(['Nanning', 'Liuzhou', 'Guilin', 'Wuzhou', 'Beihai', 'Fangchenggang', 'Qinzhou', 'Guigang', 'Yulin', 'Baise', 'Hezhou', 'Hechi', 'Laibin', 'Chongzuo']),
  'Tibet': createCityObjects(['Lhasa', 'Shigatse', 'Chamdo', 'Nyingchi', 'Shannan', 'Nagqu', 'Ngari']),
  'Ningxia': createCityObjects(['Yinchuan', 'Shizuishan', 'Wuzhong', 'Guyuan', 'Zhongwei']),
  'Xinjiang': createCityObjects(['Ürümqi', 'Karamay', 'Turpan', 'Hami', 'Changji', 'Bortala', 'Bayingolin', 'Aksu', 'Kizilsu', 'Kashgar', 'Hotan', 'Ili', 'Tacheng', 'Altay']),
  'Hong Kong': createCityObjects(['Central and Western', 'Wan Chai', 'Eastern', 'Southern', 'Yau Tsim Mong', 'Sham Shui Po', 'Kowloon City', 'Wong Tai Sin', 'Kwun Tong', 'Tsuen Wan', 'Tuen Mun', 'Yuen Long', 'North', 'Tai Po', 'Sha Tin', 'Sai Kung', 'Islands']),
  'Macau': createCityObjects(['Macau Peninsula', 'Taipa', 'Coloane'])
};
